name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}  
      run: dotnet run --project build/_build.csproj Publish
